### ISSUE TITLE
Indicator is not defined

### ISSUE THREAD

**Issue by dj-ds** [KPS250/React-Native-FlatList-Slider#3]
Facing this when Installed the library and imported 
![Simulator Screen Shot - iPhone 11 - 2020-09-08 at 14 48 45](https://user-images.githubusercontent.com/60089032/92458284-ce0bbc80-f1e2-11ea-84e4-290c31fef762.png)

**Comment by dwijonarko** [comment]
Is this already fixed? 

just restart server and re run `npx react-native run-android` again to fix this

**Comment by petrovi4** [comment]
I have a similar error. Only, it appears when I try to run debug for the web platform
<img width="500" alt="Screenshot 2020-10-31 at 16 10 22" src="https://user-images.githubusercontent.com/178891/97780145-d4d7ff80-1b93-11eb-8a31-f4d7dce25278.png">

upd.
It seems that the reason is that the compiler does not correctly perceive this format of the component definition. There's no mistake:
```javascript
export default function Indicator({
	itemCount,
	currentIndex,
	indicatorStyle,
	indicatorContainerStyle,
	indicatorActiveColor,
	indicatorInActiveColor,
	indicatorActiveWidth = 6,
}) {
	return (
...
```
